# Generated by Django 4.1.1 on 2022-09-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='price_day',
            field=models.IntegerField(default=100),
        ),
    ]
