# Generated by Django 4.1.1 on 2022-10-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car_Rental', '0004_rename_price_details_price_for_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.TextField(max_length=550),
        ),
    ]
